# Day 3

importing numpy

In [12]:
import numpy as np

array creation

In [14]:
l1 = [3.4,3,1,5,3,'python',True]

In [13]:
l5 = np.array(l1)
l5

array(['3.4', '3', '1', '5', '3', 'python', 'True'], dtype='<U32')

2D array

In [5]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

Type of array

In [6]:
type(arr3)

numpy.ndarray

check dimention in array

In [7]:
arr3.ndim

2

In [8]:
mat = np.matrix([1,2,3,4])

In [9]:
type(mat)

numpy.matrix

In [10]:
np.matrix([[1,2],[3,4],[5,6]])

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
np.matrix([[[1,2],[3,4],[5,6]]])

ValueError: matrix must be 2-dimensional

In [ ]:
l = [1,2,3]
np.array(l)

array([1, 2, 3])

convert matrix to array

In [ ]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [ ]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [ ]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [ ]:
t = ([1,2,3],[4,5,6])

In [ ]:
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
l = [12,3,4,5,65]

In [ ]:
arr = np.array(l)

In [ ]:
arr

array([12,  3,  4,  5, 65])

In [ ]:
l = [1,2,3,4,5]
l[0] = 100
l

[100, 2, 3, 4, 5]

Shallow Copy (Also changing in original)

In [ ]:
b = arr

In [ ]:
b

array([12,  3,  4,  5, 65])

In [ ]:
b[0] = 700
b

array([700,   3,   4,   5,  65])

In [ ]:
arr

array([700,   3,   4,   5,  65])

In [ ]:
arr1  = np.fromfunction(lambda i, j: i <= j,(3,3))
arr1

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [ ]:
arr1  = np.fromfunction(lambda i, j: i * j,(3,3))
arr1

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [ ]:
iterable = (i for i in range(5))
iterable

<generator object <genexpr> at 0x000001D96BE2D480>

In [ ]:
np.fromiter(iterable,int)

array([0, 1, 2, 3, 4])

In [ ]:
np.fromstring("100 200 300 400 500",sep=' ',dtype=int)

array([100, 200, 300, 400, 500])

In [ ]:
string = "dhruv,aarushi,abhishek"
string1 = string.split(",")
np.array(string1)

array(['dhruv', 'aarushi', 'abhishek'], dtype='<U8')

In [ ]:
np.fromstring("a b c",sep=" ")

TypeError: data type 'dhruv' not understood

# Day 3

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [ ]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [ ]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

[0., 0., 0., 0., 0.]

Q. if you got below 500 rank in an entrance test , you will get cse -- you will be getting  admission in the university else you will join in local college of yoour state if you get admission in an  university , you may get the top tier companies for placement or if you in any local college in that if that college rank state level is good , you may get some low level placements or if that college rank is not good of that state , you may not get placements.

In [ ]:
rank = int(input("Enter Your rank in entrance test: "))
if rank<=500:
    print("you will be getting  admission in the university")
    print("You may get the top tier companies for placement")
else:
    print("you will join in local college of yoour state")
    ch = input("Is your college rank Good/Bad")
    if(ch.lower() == "good"):
        print("you may get some low level placements")
    else:
        print("you may not get placements")



you will join in local college of yoour state
you may get some low level placements


In [22]:
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
arr = arr * 2
arr

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [27]:
arr + 3

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.empty((3,4))

array([[1.13495304e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 3.99778316e+175, 5.24164586e+174,
        1.50317657e+161],
       [1.51872046e-047, 4.28264514e-037, 1.00570893e-070,
        1.48976663e+161]])

In [30]:
import random

In [33]:
random.choice((1,2,3,4,5,6))

5

In [36]:
random.choice("Harshit")

'a'

In [40]:
random.randrange(1,20)

6

In [48]:
random.random()

0.5290152242237515

In [49]:
l = [1,2,3,4,5,6]
l

[1, 2, 3, 4, 5, 6]

In [51]:
random.shuffle(l)
l

[3, 6, 5, 1, 2, 4]

In [52]:
np.random.random_sample((5,))

array([0.9720611 , 0.11356133, 0.64838535, 0.71610405, 0.18493958])

In [53]:
np.random.rand(1)

array([0.23620788])

In [54]:
np.random.rand(2,3)

array([[0.24751795, 0.01993572, 0.37703105],
       [0.9686595 , 0.28454782, 0.13989465]])

In [57]:
arr = np.random.randint(1,5,size=(1,4))
arr, arr.ndim, arr.size

(array([[3, 2, 4, 4]], dtype=int32), 2, 4)

In [58]:
arr1 = np.random.randint(1,5,size=(3,4))
arr1

array([[2, 2, 1, 4],
       [3, 1, 2, 3],
       [1, 3, 4, 2]], dtype=int32)

In [60]:
arr2 = arr1.reshape(2,6)
arr2

array([[2, 2, 1, 4, 3, 1],
       [2, 3, 1, 3, 4, 2]], dtype=int32)