# Day 3

importing numpy

In [1]:
import numpy as np

array creation

In [2]:
l1 = [3.4,3,1,5,3,'python',True]

In [4]:
l5 = np.array(l1)
l5

array(['3.4', '3', '1', '5', '3', 'python', 'True'], dtype='<U32')

2D array

In [5]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

Type of array

In [6]:
type(arr3)

numpy.ndarray

check dimention in array

In [7]:
arr3.ndim

2

In [8]:
mat = np.matrix([1,2,3,4])

In [9]:
type(mat)

numpy.matrix

In [10]:
np.matrix([[1,2],[3,4],[5,6]])

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
np.matrix([[[1,2],[3,4],[5,6]]])

ValueError: matrix must be 2-dimensional

In [12]:
l = [1,2,3]
np.array(l)

array([1, 2, 3])

convert matrix to array

In [13]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [14]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [15]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [16]:
t = ([1,2,3],[4,5,6])

In [17]:
type(t)

tuple

In [18]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
l = [12,3,4,5,65]

In [20]:
arr = np.array(l)

In [21]:
arr

array([12,  3,  4,  5, 65])

In [22]:
l = [1,2,3,4,5]
l[0] = 100
l

[100, 2, 3, 4, 5]

Shallow Copy (Also changing in original)

In [23]:
b = arr

In [24]:
b

array([12,  3,  4,  5, 65])

In [25]:
b[0] = 700
b

array([700,   3,   4,   5,  65])

In [26]:
arr

array([700,   3,   4,   5,  65])

In [30]:
arr1  = np.fromfunction(lambda i, j: i <= j,(3,3))
arr1

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [31]:
arr1  = np.fromfunction(lambda i, j: i * j,(3,3))
arr1

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [35]:
iterable = (i for i in range(5))
iterable

<generator object <genexpr> at 0x000001D96BE2D480>

In [36]:
np.fromiter(iterable,int)

array([0, 1, 2, 3, 4])

In [39]:
np.fromstring("100 200 300 400 500",sep=' ',dtype=int)

array([100, 200, 300, 400, 500])

In [42]:
string = "dhruv,aarushi,abhishek"
string1 = string.split(",")
np.array(string1)

array(['dhruv', 'aarushi', 'abhishek'], dtype='<U8')

In [43]:
np.fromstring("a b c",sep=" ",dtype=str)

ValueError: zero-valued itemsize