# Day 03

importing numpy

In [62]:
import numpy as np

array creation

In [63]:
l1 = [3.4,3,1,5,3,'python',True]

In [64]:
l5 = np.array(l1)
l5

array(['3.4', '3', '1', '5', '3', 'python', 'True'], dtype='<U32')

2D array

In [65]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

Type of array

In [66]:
type(arr3)

numpy.ndarray

check dimention in array

In [67]:
arr3.ndim

2

In [68]:
mat = np.matrix([1,2,3,4])

In [69]:
type(mat)

numpy.matrix

In [70]:
np.matrix([[1,2],[3,4],[5,6]])

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [71]:
np.matrix([[[1,2],[3,4],[5,6]]])

ValueError: matrix must be 2-dimensional

In [ ]:
l = [1,2,3]
np.array(l)

array([1, 2, 3])

convert matrix to array

In [ ]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [ ]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [ ]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [ ]:
t = ([1,2,3],[4,5,6])

In [ ]:
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
l = [12,3,4,5,65]

In [ ]:
arr = np.array(l)

In [ ]:
arr

array([12,  3,  4,  5, 65])

In [ ]:
l = [1,2,3,4,5]
l[0] = 100
l

[100, 2, 3, 4, 5]

Shallow Copy (Also changing in original)

In [ ]:
b = arr

In [ ]:
b

array([12,  3,  4,  5, 65])

In [ ]:
b[0] = 700
b

array([700,   3,   4,   5,  65])

In [ ]:
arr

array([700,   3,   4,   5,  65])

In [ ]:
arr1  = np.fromfunction(lambda i, j: i <= j,(3,3))
arr1

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [ ]:
arr1  = np.fromfunction(lambda i, j: i * j,(3,3))
arr1

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [ ]:
iterable = (i for i in range(5))
iterable

<generator object <genexpr> at 0x000001D96BE2D480>

In [ ]:
np.fromiter(iterable,int)

array([0, 1, 2, 3, 4])

In [ ]:
np.fromstring("100 200 300 400 500",sep=' ',dtype=int)

array([100, 200, 300, 400, 500])

In [ ]:
string = "dhruv,aarushi,abhishek"
string1 = string.split(",")
np.array(string1)

array(['dhruv', 'aarushi', 'abhishek'], dtype='<U8')

In [ ]:
np.fromstring("a b c",sep=" ")

TypeError: data type 'dhruv' not understood

# Day 04

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [ ]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [ ]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

[0., 0., 0., 0., 0.]

Q. if you got below 500 rank in an entrance test , you will get cse -- you will be getting  admission in the university else you will join in local college of yoour state if you get admission in an  university , you may get the top tier companies for placement or if you in any local college in that if that college rank state level is good , you may get some low level placements or if that college rank is not good of that state , you may not get placements.

In [ ]:
rank = int(input("Enter Your rank in entrance test: "))
if rank<=500:
    print("you will be getting  admission in the university")
    print("You may get the top tier companies for placement")
else:
    print("you will join in local college of yoour state")
    ch = input("Is your college rank Good/Bad")
    if(ch.lower() == "good"):
        print("you may get some low level placements")
    else:
        print("you may not get placements")



you will join in local college of yoour state
you may get some low level placements


In [ ]:
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr = arr * 2
arr

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
arr + 3

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.empty((3,4))

array([[1.13495304e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 3.99778316e+175, 5.24164586e+174,
        1.50317657e+161],
       [1.51872046e-047, 4.28264514e-037, 1.00570893e-070,
        1.48976663e+161]])

In [ ]:
import random

In [ ]:
random.choice((1,2,3,4,5,6))

5

In [ ]:
random.choice("Harshit")

'a'

In [ ]:
random.randrange(1,20)

6

In [ ]:
random.random()

0.5290152242237515

In [ ]:
l = [1,2,3,4,5,6]
l

[1, 2, 3, 4, 5, 6]

In [ ]:
random.shuffle(l)
l

[3, 6, 5, 1, 2, 4]

In [ ]:
np.random.random_sample((5,))

array([0.9720611 , 0.11356133, 0.64838535, 0.71610405, 0.18493958])

In [ ]:
np.random.rand(1)

array([0.23620788])

In [ ]:
np.random.rand(2,3)

array([[0.24751795, 0.01993572, 0.37703105],
       [0.9686595 , 0.28454782, 0.13989465]])

In [ ]:
arr = np.random.randint(1,5,size=(1,4))
arr, arr.ndim, arr.size

(array([[3, 2, 4, 4]], dtype=int32), 2, 4)

In [ ]:
arr1 = np.random.randint(1,5,size=(3,4))
arr1

array([[2, 2, 1, 4],
       [3, 1, 2, 3],
       [1, 3, 4, 2]], dtype=int32)

In [ ]:
arr2 = arr1.reshape(2,6)
arr2

array([[2, 2, 1, 4, 3, 1],
       [2, 3, 1, 3, 4, 2]], dtype=int32)

# Day 05

In [ ]:
np.random.rand(1)

array([0.58053444])

In [ ]:
np.random.random_sample((5,))

array([0.96271451, 0.93748561, 0.39541588, 0.49960787, 0.4976886 ])

In [ ]:
np.random.random_sample()

0.5506986623683975

In [ ]:
np.random.rand(2,3)

array([[0.76945454, 0.72316647, 0.33152148],
       [0.8156216 , 0.97759724, 0.0734913 ]])

In [ ]:
np.random.randn(2,3)

array([[-0.31735607,  0.00915797,  0.48841089],
       [-0.01928875, -1.98247659, -0.8187805 ]])

In [ ]:
arr = np.random.randint(1,5,size=(3,4))
arr, arr.ndim, arr.shape

(array([[3, 2, 2, 2],
        [1, 4, 1, 4],
        [1, 4, 2, 3]], dtype=int32),
 2,
 (3, 4))

In [ ]:
arr.reshape(12,1)

array([[3],
       [2],
       [2],
       [2],
       [1],
       [4],
       [1],
       [4],
       [1],
       [4],
       [2],
       [3]], dtype=int32)

In [ ]:
arr.reshape(1,12)

array([[3, 2, 2, 2, 1, 4, 1, 4, 1, 4, 2, 3]], dtype=int32)

In [ ]:
arr.reshape(1,-1)

array([[3, 2, 2, 2, 1, 4, 1, 4, 1, 4, 2, 3]], dtype=int32)

In [ ]:
arr.reshape(2,-1)

array([[3, 2, 2, 2, 1, 4],
       [1, 4, 1, 4, 2, 3]], dtype=int32)

In [ ]:
arr1 = arr.reshape(-1,4)
arr1, arr1.size

(array([[3, 2, 2, 2],
        [1, 4, 1, 4],
        [1, 4, 2, 3]], dtype=int32),
 12)

In [ ]:
arr1.reshape(2,2,3)

array([[[3, 2, 2],
        [2, 1, 4]],

       [[1, 4, 1],
        [4, 2, 3]]], dtype=int32)

In [ ]:
arr1.reshape(1,2,2,3), arr1.reshape(1,2,2,3).ndim

(array([[[[3, 2, 2],
          [2, 1, 4]],
 
         [[1, 4, 1],
          [4, 2, 3]]]], dtype=int32),
 4)

In [ ]:
arr1[arr1>3], arr1[arr1<3]

(array([4, 4, 4], dtype=int32), array([2, 2, 2, 1, 1, 1, 2], dtype=int32))

In [ ]:
arr1[0]

array([3, 2, 2, 2], dtype=int32)

In [ ]:
arr1[0][0]

np.int32(3)

In [ ]:
arr1

array([[3, 2, 2, 2],
       [1, 4, 1, 4],
       [1, 4, 2, 3]], dtype=int32)

In [ ]:
arr1[0:3]

array([[3, 2, 2, 2],
       [1, 4, 1, 4],
       [1, 4, 2, 3]], dtype=int32)

In [76]:
arr1[0:3:2][0:3:2]

array([[1, 1, 2]], dtype=int32)

In [79]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

arr1, arr2

(array([[2, 1, 1],
        [2, 1, 2],
        [1, 1, 1]], dtype=int32),
 array([[1, 2, 2],
        [2, 2, 2],
        [1, 2, 1]], dtype=int32))

In [80]:
arr1 @ arr2

array([[ 5,  8,  7],
       [ 6, 10,  8],
       [ 4,  6,  5]], dtype=int32)

In [81]:
np.dot(arr1,arr2)

array([[ 5,  8,  7],
       [ 6, 10,  8],
       [ 4,  6,  5]], dtype=int32)

In [82]:
arr1 = np.zeros((3,4))

In [83]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
arr+5

array([[8, 7, 7, 7],
       [6, 9, 6, 9],
       [6, 9, 7, 8]], dtype=int32)

In [87]:
a = np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [88]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [89]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [90]:
arr1, arr2

(array([[2, 1, 2],
        [1, 2, 2],
        [2, 2, 1]], dtype=int32),
 array([[1, 1, 1],
        [2, 1, 1],
        [1, 2, 2]], dtype=int32))

In [91]:
arr1.flatten()

array([2, 1, 2, 1, 2, 2, 2, 2, 1], dtype=int32)

In [92]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [93]:
arr.ndim

1

In [94]:
np.expand_dims(arr,axis=0)

array([[1, 2, 3, 4]])

In [95]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [96]:
np.expand_dims(arr,axis=1).ndim

2

In [98]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
arr.ndim

2

In [100]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
np.expand_dims(arr,axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [103]:
np.expand_dims(arr,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [104]:
a = np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [105]:
a.ndim

2

In [108]:
np.squeeze(a)

array([1, 2, 3])

In [109]:
a

array([[1],
       [2],
       [3]])

In [110]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [111]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [2, 2, 1]], dtype=int32)

In [112]:
np.repeat(arr1,2)

array([2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1], dtype=int32)

In [113]:
np.repeat(arr1,2,axis=0)

array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 2],
       [1, 2, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [114]:
np.roll(a,-1)

array([[2],
       [3],
       [1]])

In [115]:
c = np.array([[1,2],[3,4],[5,6],[7,8]])
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [119]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [117]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [120]:
arr1 + arr2

array([[3, 2, 3],
       [3, 3, 3],
       [3, 4, 3]], dtype=int32)

In [121]:
arr1 * arr2

array([[2, 1, 2],
       [2, 2, 2],
       [2, 4, 2]], dtype=int32)

In [122]:
arr1 - arr2

array([[ 1,  0,  1],
       [-1,  1,  1],
       [ 1,  0, -1]], dtype=int32)

In [123]:
d = np.array(["abhay","arushi"])
d

array(['abhay', 'arushi'], dtype='<U6')

In [124]:
np.char.upper(d)

array(['ABHAY', 'ARUSHI'], dtype='<U6')

In [125]:
np.char.capitalize(d)

array(['Abhay', 'Arushi'], dtype='<U6')

In [126]:
np.sin(arr1)

array([[0.90929743, 0.84147098, 0.90929743],
       [0.84147098, 0.90929743, 0.90929743],
       [0.90929743, 0.90929743, 0.84147098]])

In [127]:
np.cos(arr1)

array([[-0.41614684,  0.54030231, -0.41614684],
       [ 0.54030231, -0.41614684, -0.41614684],
       [-0.41614684, -0.41614684,  0.54030231]])

In [128]:
np.tan(arr1)

array([[-2.18503986,  1.55740772, -2.18503986],
       [ 1.55740772, -2.18503986, -2.18503986],
       [-2.18503986, -2.18503986,  1.55740772]])

In [129]:
np.log(arr1)

array([[0.69314718, 0.        , 0.69314718],
       [0.        , 0.69314718, 0.69314718],
       [0.69314718, 0.69314718, 0.        ]])

In [130]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [132]:
np.power(arr1,3)

array([[8, 1, 8],
       [1, 8, 8],
       [8, 8, 1]], dtype=int32)

In [133]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [2, 2, 1]], dtype=int32)

In [134]:
np.mean(arr1)

np.float64(1.6666666666666667)

In [135]:
np.max(arr1)

np.int32(2)

In [139]:
np.std(arr1)

np.float64(0.4714045207910317)

In [138]:
np.var(arr1)

np.float64(0.2222222222222222)

In [141]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        ]])

In [155]:
e = np.array([5,6,2,1,-4])
e

array([ 5,  6,  2,  1, -4])

In [148]:
np.sort(e)

array([1, 2, 5, 6])

In [153]:
np.searchsorted(e,3)

np.int64(4)

In [149]:
np.count_nonzero(e)

4

In [150]:
e[e>0]

array([5, 6, 2, 1])

In [151]:
np.where(e)

(array([0, 1, 2, 3]),)

In [158]:
np.extract(e>0,e)

array([5, 6, 2, 1])

In [157]:
e.byteswap()

array([ 360287970189639680,  432345564227567616,  144115188075855872,
         72057594037927936, -216172782113783809])